namespace GHelper.Hardware.Hp;

public static class HpDiagnosticDashboardFormatter
{
    public const string NotAvailable = "Not available";
    public const string LegacyReportSchema = "Legacy / unknown";
    public const string RawFanLevelWarning = "Raw values are not RPM or percent.";
    public const string FanControlStatus = "Blocked - " + HpDiagnosticStatusText.FanControlNotImplemented;
    public const string SetFanMaxStatus = HpDiagnosticStatusText.SetFanMaxNoGo;
    public const string SetFanMaxReadinessStatus = "NO-GO";
    public const string SetFanMaxFirstWriteGateNotSatisfied = "False - not satisfied";
    public const string SetFanMaxFirstWriteGateMissingOldReportReason = "Missing first-write gate field(s) in cached/old report; failing closed to NO-GO until exact-device proof is present.";
    public const string SetFanMaxFirstWriteGateUnexpectedReportReason = "Cached report contains optimistic first-write gate data; failing closed to NO-GO.";
    public const string SetFanMaxInputLengthUnset = "Unset / not validated";
    public const string SetFanMaxPayloadLengthNotSelected = "Not selected";
    public const string SetFanMaxEvidenceMissing = "Missing / not proven";
    public const string SetFanMaxExperimentalPayloadUnknown = "Unknown / not selected";
    public const string SetFanMaxPhysicalResponseUnknown = "Unknown - missing or unrecognized experimental evidence";
    public const string SetFanMaxReadbackNotReliable = "False - FanMaxGet is not a reliable sole success criterion";
    public const string SetFanMaxDeveloperExperimentAllowed = "True - four-byte controlled developer experiments only";
    public const string SetFanMaxDeveloperExperimentPayload = "FourByte - developer experiment only";
    public const string SetFanMaxDeveloperExperimentNotAllowed = "False - developer experiment allowance is missing or invalid";
    public const string SetFanMaxDeveloperExperimentPayloadUnknown = "Unknown - developer experiment payload is missing or invalid";
    public const string SetFanMaxNormalControlNotValidated = "False - normal control is not validated";
    public const string SetFanMaxUserFacingControlNotAllowed = "False - user-facing control is not allowed";
    public const string PulseHistoryNotAvailable = "No pulse history available";
    public const string PulseHistoryNormalControlDisabled = "Disabled - normal fan control remains NO-GO";

    public static HpDiagnosticDashboardHealthSummary BuildHealthSummary(HpDiagnosticDashboardInput input)
    {
        return new HpDiagnosticDashboardHealthSummary(
            input.IsHpVictusDetected == true ? "Ready" : NotAvailable,
            ClassifyAvailability(
                input.RootWmiReadiness,
                input.HpqBIntMReadiness,
                input.HpqBDataInReadiness),
            ClassifyAvailability(input.SystemDesignDataDecodeStatus, input.SoftwareFanControlSupport),
            ClassifyAvailability(input.FanCount, input.MaxFanState, input.Fan1RawLevel, input.Fan2RawLevel),
            SetFanMaxStatus);
    }

    public static string FormatHealthSummary(HpDiagnosticDashboardHealthSummary summary)
    {
        return "Health: Device " + summary.DeviceStatus +
            " | WMI " + summary.WmiStatus +
            " | Telemetry " + summary.ReadOnlyTelemetryStatus +
            " | Fan read-only " + summary.FanReadOnlyStatus +
            " | Fan control " + summary.FanControlStatus;
    }

    public static IReadOnlyList<HpDiagnosticDashboardSection> BuildSections(HpDiagnosticDashboardInput input)
    {
        return
        [
            new("Report metadata",
            [
                Row("Schema version", FormatReportSchemaVersion(input.ReportSchemaVersion)),
                Row("Generated by", input.ReportGeneratedBy),
                Row("Report mode", input.ReportMode),
                Row("Report source", input.ReportSource),
                Row("Last generated", FormatReportTimestamp(input.ReportGeneratedAt))
            ]),
            new("Device",
            [
                Row(HpDiagnosticStatusText.ReadOnlyDiagnostic, "Cached report and startup snapshot only; no UI action invokes WMI."),
                Row("HP/Victus detected", input.IsHpVictusDetected == true ? "Detected" : NotAvailable),
                Row("Manufacturer", input.Manufacturer),
                Row("Model", input.Model),
                Row("SKU", input.Sku),
                Row("BIOS version", input.BiosVersion)
            ]),
            new("WMI readiness",
            [
                Row(@"root\wmi", input.RootWmiReadiness),
                Row("hpqBIntM", input.HpqBIntMReadiness),
                Row("hpqBDataIn", input.HpqBDataInReadiness)
            ]),
            new("Read-only telemetry",
            [
                Row("SystemDesignData decoded", input.SystemDesignDataDecodeStatus),
                Row("Thermal policy version", input.ThermalPolicyVersion),
                Row("Software fan control declared by firmware", input.SoftwareFanControlSupport)
            ]),
            new("Fan read-only status",
            [
                Row("Fan count", input.FanCount),
                Row("Max fan state", input.MaxFanState),
                Row("Fan 1 raw level byte", input.Fan1RawLevel),
                Row("Fan 2 raw level byte", input.Fan2RawLevel),
                Row("Raw level data", RawFanLevelWarning)
            ]),
            new("Latest SetFanMax pulse/history",
            [
                Row("Status", input.SetFanMaxPulseHistoryStatus ?? PulseHistoryNotAvailable),
                Row("Latest pulse timestamp", input.SetFanMaxPulseTimestamp),
                Row("Payload used", input.SetFanMaxPulsePayload),
                Row("WriteExecuted", input.SetFanMaxPulseWriteExecuted),
                Row("Enable command succeeded", input.SetFanMaxPulseEnableCommandSucceeded),
                Row("Restore command succeeded", input.SetFanMaxPulseRestoreCommandSucceeded),
                Row("Physical fan response observed", input.SetFanMaxPulsePhysicalFanResponseObserved),
                Row("Restore observed", input.SetFanMaxPulseRestoreObserved),
                Row("Readback reliability", input.SetFanMaxPulseReadbackReliability),
                Row("Experimental outcome classification", input.SetFanMaxPulseOutcomeClassification),
                Row("Notes summary", input.SetFanMaxPulseNotesSummary),
                Row("Evidence scope", "Developer-only evidence - no pulse/run action is available"),
                Row("Normal fan control", PulseHistoryNormalControlDisabled)
            ]),
            new("HP fan proof-gap analysis",
            [
                Row("Evidence sources", input.FanProofGapEvidenceSources),
                Row("Developer-only pulse", input.FanProofGapDeveloperPulseDecision),
                Row("DeviceValidatedInputLength", input.FanProofGapDeviceValidatedInputLengthDecision),
                Row("FanMaxGet reliability", input.FanProofGapFanMaxGetDecision),
                Row("FanGetLevel interpretation", input.FanProofGapFanGetLevelDecision),
                Row("Restore verification", input.FanProofGapRestoreVerificationDecision),
                Row("Repeatability", input.FanProofGapRepeatabilityDecision),
                Row("Thermal/power safety", input.FanProofGapThermalPowerSafetyDecision),
                Row("Normal fan-control readiness", input.FanProofGapNormalFanControlDecision)
            ]),
            new("SetFanMax evidence readiness",
            [
                Row("Current status", SetFanMaxReadinessStatus),
                Row("First-write gate status", FormatFirstWriteGateStatus(input.SetFanMaxFirstWriteGateStatus)),
                Row("First-write gate satisfied", FormatFirstWriteGateSatisfied(input.SetFanMaxFirstWriteGateSatisfied)),
                Row("First-write gate reason", FormatFirstWriteGateReason(
                    input.SetFanMaxFirstWriteGateStatus,
                    input.SetFanMaxFirstWriteGateSatisfied,
                    input.SetFanMaxFirstWriteGateReason)),
                Row("Experimental payload candidate", FormatExperimentalPayloadCandidate(input.SetFanMaxExperimentalPayloadCandidate)),
                Row("Physical response observed", FormatPhysicalResponseObserved(
                    input.SetFanMaxExperimentalPayloadCandidate,
                    input.SetFanMaxPhysicalResponseObserved,
                    input.SetFanMaxPhysicalResponseConfirmationCount)),
                Row("Physical response confirmation count", FormatPhysicalResponseConfirmationCount(
                    input.SetFanMaxExperimentalPayloadCandidate,
                    input.SetFanMaxPhysicalResponseObserved,
                    input.SetFanMaxPhysicalResponseConfirmationCount)),
                Row("Readback reliable", FormatReadbackReliable(input.SetFanMaxReadbackReliable)),
                Row("Developer-only experiment allowed", FormatDeveloperExperimentAllowed(
                    input.SetFanMaxDeveloperExperimentAllowed,
                    input.SetFanMaxDeveloperExperimentPayload)),
                Row("Developer-only experiment payload", FormatDeveloperExperimentPayload(
                    input.SetFanMaxDeveloperExperimentAllowed,
                    input.SetFanMaxDeveloperExperimentPayload)),
                Row("Normal control validated", FormatNormalControlValidated(input.SetFanMaxNormalControlValidated)),
                Row("User-facing control allowed", FormatUserFacingControlAllowed(input.SetFanMaxUserFacingControlAllowed)),
                Row("Fan write implemented", FormatEvidenceWriteImplemented(input.SetFanMaxWriteImplemented)),
                Row("Fan write allowed", FormatEvidenceWriteAllowed(input.SetFanMaxWriteAllowed)),
                Row("DeviceValidatedInputLength", FormatDeviceValidatedInputLength(input.SetFanMaxDeviceValidatedInputLength)),
                Row("Payload length decision", SetFanMaxPayloadLengthNotSelected),
                Row("Exact device payload length", SetFanMaxEvidenceMissing),
                Row("Restore/disable behavior proof", SetFanMaxEvidenceMissing),
                Row("Thermal observation proof", SetFanMaxEvidenceMissing),
                Row("AC/battery/power-state proof", SetFanMaxEvidenceMissing),
                Row("Failure/recovery proof", SetFanMaxEvidenceMissing),
                Row("Human approval checkpoint", SetFanMaxEvidenceMissing),
                Row("Report blocked reason", input.SetFanMaxBlockedReason),
                Row("Report next required proof", input.SetFanMaxNextRequiredProof)
            ]),
            new("Safety / NO-GO status",
            [
                Row("Fan control", FanControlStatus),
                Row("SetFanMax", SetFanMaxStatus),
                Row("SetFanMax write implemented", input.SetFanMaxWriteImplemented),
                Row("SetFanMax write allowed", input.SetFanMaxWriteAllowed),
                Row("Blocked reason", input.SetFanMaxBlockedReason),
                Row("Next required proof", input.SetFanMaxNextRequiredProof)
            ]),
            new("Missing-data guidance",
            [
                Row("Explicit probe data", HpDiagnosticStatusText.NormalHpModeDoesNotRunExplicitProbes),
                Row("Developer-only tests", HpDiagnosticStatusText.ExplicitTestsAreDeveloperOnly),
                Row("Fan control", HpDiagnosticStatusText.FanControlNotImplemented),
                Row("SetFanMax", HpDiagnosticStatusText.SetFanMaxNoGo)
            ])
        ];
    }

    public static IReadOnlyList<HpDiagnosticDashboardSection> BuildUserSummary(HpDiagnosticUserSummaryInput input)
    {
        return
        [
            new("Device",
            [
                UserRow("Model", input.Model),
                UserRow("SKU", input.Sku),
                UserRow("BIOS", input.BiosVersion),
                UserRow("HP/Victus detection", input.HpVictusDetection),
                UserRow("Fan count", input.FanCount),
                UserRow("Thermal policy", input.ThermalPolicy)
            ]),
            new("Live status",
            [
                UserRow("CPU Load", input.CpuLoad),
                UserRow("GPU Temp", input.GpuTemperature),
                UserRow("Battery / AC", input.BatteryPower),
                UserRow("Refresh Rate", input.RefreshRate),
                UserRow("CPU Temp", input.CpuTemperature),
                UserRow("Fan RPM", input.FanRpm)
            ]),
            new("Capabilities",
            [
                UserRow("GPU Switching", input.GpuSwitchingCapability),
                UserRow("Keyboard Lighting", input.KeyboardBacklightCapability),
                UserRow("Battery Care", input.BatteryCareCapability),
                UserRow("Fan Control", input.FanControlStatus, blocked: true)
            ])
        ];
    }

    public static string BuildSummary(HpDiagnosticDashboardInput input)
    {
        return string.Join(
            Environment.NewLine,
            BuildSections(input)
                .SelectMany(section => section.Rows)
                .Select(row => row.Label + ": " + row.Value));
    }

    public static string FormatWriteImplementationStatus(bool? value) => value switch
    {
        true => "Implemented",
        false => "Not implemented",
        _ => NotAvailable
    };

    public static string FormatWriteAllowedStatus(bool? value) => value switch
    {
        true => "Allowed",
        false => "Blocked",
        _ => NotAvailable
    };

    public static string FormatDeviceValidatedInputLength(string? value)
    {
        return int.TryParse(value, out int length) && length is 1 or 4
            ? length + (length == 1 ? " byte reported; not approved" : " bytes reported; not approved")
            : SetFanMaxInputLengthUnset;
    }

    public static string FormatFirstWriteGateStatus(string? value)
    {
        return string.Equals(value, "GO", StringComparison.OrdinalIgnoreCase)
            ? "Blocked - unexpected GO state"
            : SetFanMaxReadinessStatus;
    }

    public static string FormatFirstWriteGateSatisfied(string? value)
    {
        return string.Equals(value, bool.TrueString, StringComparison.OrdinalIgnoreCase)
            ? "Blocked - unexpected satisfied state"
            : SetFanMaxFirstWriteGateNotSatisfied;
    }

    public static string FormatFirstWriteGateReason(string? status, string? satisfied, string? reason)
    {
        if (string.Equals(status, "GO", StringComparison.OrdinalIgnoreCase) ||
            string.Equals(satisfied, bool.TrueString, StringComparison.OrdinalIgnoreCase))
        {
            return SetFanMaxFirstWriteGateUnexpectedReportReason;
        }

        if (string.IsNullOrWhiteSpace(status) ||
            string.IsNullOrWhiteSpace(satisfied) ||
            string.IsNullOrWhiteSpace(reason))
        {
            return SetFanMaxFirstWriteGateMissingOldReportReason;
        }

        return reason;
    }

    public static string FormatExperimentalPayloadCandidate(string? value) =>
        string.Equals(value, "FourByte", StringComparison.OrdinalIgnoreCase)
            ? "FourByte - experimental only"
            : SetFanMaxExperimentalPayloadUnknown;

    public static string FormatPhysicalResponseObserved(string? candidate, string? observed, string? confirmationCount) =>
        HasRecognizedExperimentalPhysicalResponse(candidate, observed, confirmationCount)
            ? "True - observed in two manual four-byte experiments; experimental only"
            : SetFanMaxPhysicalResponseUnknown;

    public static string FormatPhysicalResponseConfirmationCount(string? candidate, string? observed, string? value) =>
        HasRecognizedExperimentalPhysicalResponse(candidate, observed, value)
            ? "2 - manual four-byte confirmation records"
            : "Unknown";

    public static string FormatReadbackReliable(string? value) =>
        string.Equals(value, bool.TrueString, StringComparison.OrdinalIgnoreCase)
            ? "False - unexpected reliable readback claim; failing closed"
            : SetFanMaxReadbackNotReliable;

    public static string FormatDeveloperExperimentAllowed(string? allowed, string? payload) =>
        HasRecognizedDeveloperExperimentAllowance(allowed, payload)
            ? SetFanMaxDeveloperExperimentAllowed
            : SetFanMaxDeveloperExperimentNotAllowed;

    public static string FormatDeveloperExperimentPayload(string? allowed, string? payload) =>
        HasRecognizedDeveloperExperimentAllowance(allowed, payload)
            ? SetFanMaxDeveloperExperimentPayload
            : SetFanMaxDeveloperExperimentPayloadUnknown;

    public static string FormatNormalControlValidated(string? value) =>
        string.Equals(value, bool.TrueString, StringComparison.OrdinalIgnoreCase)
            ? "False - unexpected normal-control validation claim; failing closed"
            : SetFanMaxNormalControlNotValidated;

    public static string FormatUserFacingControlAllowed(string? value) =>
        string.Equals(value, bool.TrueString, StringComparison.OrdinalIgnoreCase)
            ? "False - unexpected user-facing control claim; failing closed"
            : SetFanMaxUserFacingControlNotAllowed;

    private static string FormatEvidenceWriteImplemented(string? value)
    {
        return string.Equals(value, "Implemented", StringComparison.OrdinalIgnoreCase) ||
            string.Equals(value, bool.TrueString, StringComparison.OrdinalIgnoreCase)
            ? "Blocked - unexpected implemented state"
            : "False - not implemented";
    }

    private static string FormatEvidenceWriteAllowed(string? value)
    {
        return string.Equals(value, "Allowed", StringComparison.OrdinalIgnoreCase) ||
            string.Equals(value, bool.TrueString, StringComparison.OrdinalIgnoreCase)
            ? "Blocked - unexpected allowed state"
            : "False - blocked";
    }

    private static bool HasRecognizedExperimentalPhysicalResponse(string? candidate, string? observed, string? confirmationCount) =>
        string.Equals(candidate, "FourByte", StringComparison.OrdinalIgnoreCase) &&
        string.Equals(observed, bool.TrueString, StringComparison.OrdinalIgnoreCase) &&
        string.Equals(confirmationCount, "2", StringComparison.Ordinal);

    private static bool HasRecognizedDeveloperExperimentAllowance(string? allowed, string? payload) =>
        string.Equals(allowed, bool.TrueString, StringComparison.OrdinalIgnoreCase) &&
        string.Equals(payload, "FourByte", StringComparison.OrdinalIgnoreCase);

    public static string FormatReportSchemaVersion(string? value)
    {
        return int.TryParse(value, out int version) && version > 0
            ? "v" + version
            : LegacyReportSchema;
    }

    public static string FormatReportTimestamp(string? value)
    {
        return DateTimeOffset.TryParse(value, out DateTimeOffset timestamp)
            ? timestamp.ToString("yyyy-MM-dd HH:mm:ss zzz", System.Globalization.CultureInfo.InvariantCulture)
            : NotAvailable;
    }

    private static HpDiagnosticDashboardRow Row(string label, string? value)
    {
        string displayValue = string.IsNullOrWhiteSpace(value) ? NotAvailable : value;
        return new HpDiagnosticDashboardRow(label, displayValue, GetStatus(displayValue));
    }

    private static HpDiagnosticDashboardRow UserRow(string label, string? value, bool blocked = false)
    {
        string displayValue = string.IsNullOrWhiteSpace(value) ? "Unavailable" : value;
        HpDiagnosticDashboardStatus status = blocked
            ? HpDiagnosticDashboardStatus.Blocked
            : IsUnavailableUserValue(displayValue)
                ? HpDiagnosticDashboardStatus.Normal
                : HpDiagnosticDashboardStatus.Ready;
        return new HpDiagnosticDashboardRow(label, displayValue, status);
    }

    private static bool IsUnavailableUserValue(string value) =>
        value.Contains("Unavailable", StringComparison.OrdinalIgnoreCase) ||
        value.Contains("Unknown", StringComparison.OrdinalIgnoreCase) ||
        value.Contains("Stale", StringComparison.OrdinalIgnoreCase) ||
        value.Contains("Not sampled", StringComparison.OrdinalIgnoreCase) ||
        value.Contains("not detected", StringComparison.OrdinalIgnoreCase) ||
        value.Contains("Not supported", StringComparison.OrdinalIgnoreCase) ||
        value.Contains("Not exposed", StringComparison.OrdinalIgnoreCase) ||
        value.Contains("No battery", StringComparison.OrdinalIgnoreCase) ||
        value.Contains("state unavailable", StringComparison.OrdinalIgnoreCase);

    private static string ClassifyAvailability(params string?[] values)
    {
        int availableCount = values.Count(value => !string.IsNullOrWhiteSpace(value) &&
            !string.Equals(value, NotAvailable, StringComparison.OrdinalIgnoreCase));

        return availableCount switch
        {
            0 => NotAvailable,
            _ when availableCount == values.Length => "Ready",
            _ => "Partial"
        };
    }

    private static HpDiagnosticDashboardStatus GetStatus(string value)
    {
        if (value.StartsWith("Ready", StringComparison.OrdinalIgnoreCase) ||
            value.StartsWith("Succeeded", StringComparison.OrdinalIgnoreCase) ||
            value.StartsWith("Enabled", StringComparison.OrdinalIgnoreCase) ||
            value.StartsWith("Declared", StringComparison.OrdinalIgnoreCase))
        {
            return HpDiagnosticDashboardStatus.Ready;
        }

        if (value.StartsWith("Blocked", StringComparison.OrdinalIgnoreCase) ||
            value.StartsWith("NO-GO", StringComparison.OrdinalIgnoreCase) ||
            value.StartsWith("False -", StringComparison.OrdinalIgnoreCase) ||
            value.StartsWith("False - blocked", StringComparison.OrdinalIgnoreCase) ||
            value.StartsWith("False - not satisfied", StringComparison.OrdinalIgnoreCase) ||
            value.StartsWith("Missing", StringComparison.OrdinalIgnoreCase) ||
            value.StartsWith("Inconclusive", StringComparison.OrdinalIgnoreCase) ||
            value.StartsWith("Raw-only", StringComparison.OrdinalIgnoreCase) ||
            value.StartsWith("Partial", StringComparison.OrdinalIgnoreCase) ||
            value.StartsWith("Unknown", StringComparison.OrdinalIgnoreCase) ||
            value.StartsWith("Cached report contains optimistic", StringComparison.OrdinalIgnoreCase) ||
            value.StartsWith("Unset", StringComparison.OrdinalIgnoreCase) ||
            value.StartsWith("Not selected", StringComparison.OrdinalIgnoreCase))
        {
            return HpDiagnosticDashboardStatus.Blocked;
        }

        if (value.StartsWith("FourByte", StringComparison.OrdinalIgnoreCase) ||
            value.StartsWith("True - observed", StringComparison.OrdinalIgnoreCase) ||
            value.StartsWith("True - four-byte", StringComparison.OrdinalIgnoreCase))
        {
            return HpDiagnosticDashboardStatus.Warning;
        }

        return HpDiagnosticDashboardStatus.Normal;
    }
}
